## Orange diseases  classification model Test model

In this notebook, we test the model trained with axelerate Keras-based framework for AI on the edge in tflite format.
1) We used the sklean metrics to test the model confusion_matrix, classification_report: 

#####  the complete information of metrics are in the documentation:   https://scikit-learn.org/stable/index.html

## Requirements

- Tensorflow
- scikit-learn
- Numpy
- os

In [49]:
# the command to install the scikit-learn and tensorflow library
# there are other ways to install you can find them at:  
#https://pypi.org/project/scikit-learn/
# https://pypi.org/project/tensorflow/
!pip install scikit-learn  
!pip install tensorflow

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
import tensorflow as tf
import numpy as np
import os

In [48]:
print(tf.__version__)
print(np.__version__)

2.6.0
1.19.5


##### Read the model by training with tflite interpreter


In [ ]:
interpreter = tf.lite.Interpreter("classifier_best_loss.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

In [51]:
class_counter = 0
frame_counter = 0

true_vec = []
pred_vec = []


path = 'dataset/canker' # path with citrus canker image 
dirlist = []
dirlist = os.listdir(path)

sm = 0
for file in dirlist:

    img = image.load_img(path+'/'+file, target_size=(224, 224)) #the format of image trained of model.tflite is [224,224]
    orange = img_to_array(img)
    orange = preprocess_input(orange)
    orange = np.expand_dims(orange, axis=0)
    interpreter.set_tensor(input_details[0]['index'],orange)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])
    (cancro,frescas,grenning,pinta) = output_data[0]
    if(frescas>cancro and frescas>pinta and frescas>grenning):
        score = 1
    elif(cancro>frescas and cancro>pinta and cancro>grenning):
        score = 0
    elif(pinta>frescas and pinta>cancro and pinta>grenning):
        score = 3
    else:
        score = 2

    sm += score
    true_vec.append(0) # true vector class number 0
    pred_vec.append(score)
    #print(predict)
    #cv2.imshow('imagem',cdist)

path = 'dataset/fresh'
dirlist = []
dirlist = os.listdir(path)

sm = 0
for file in dirlist:

    img = image.load_img(path+'/'+file, target_size=(224, 224))
    orange = img_to_array(img)
    orange = preprocess_input(orange)
    orange = np.expand_dims(orange, axis=0)
    interpreter.set_tensor(input_details[0]['index'],orange)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])
    (cancro,frescas,grenning,pinta) = output_data[0]
    if(frescas>cancro and frescas>pinta and frescas>grenning):
        score = 1
    elif(cancro>frescas and cancro>pinta and cancro>grenning):
        score = 0
    elif(pinta>frescas and pinta>cancro and pinta>grenning):
        score = 3
    else:
        score = 2

    sm += score
    true_vec.append(1) # true vector class number 1
    pred_vec.append(score)
    #print(predict)
    #cv2.imshow('imagem',cdist)

path = 'dataset/grenning'
dirlist = []
dirlist = os.listdir(path)

sm = 0
for file in dirlist:

    img = image.load_img(path+'/'+file, target_size=(224, 224))
    orange = img_to_array(img)
    orange = preprocess_input(orange)
    orange = np.expand_dims(orange, axis=0)
    interpreter.set_tensor(input_details[0]['index'],orange)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])
    (cancro,frescas,grenning,pinta) = output_data[0]
    if(frescas>cancro and frescas>pinta and frescas>grenning):
        score = 1
    elif(cancro>frescas and cancro>pinta and cancro>grenning):
        score = 0
    elif(pinta>frescas and pinta>cancro and pinta>grenning):
        score = 3
    else:
        score = 2

    sm += score
    true_vec.append(2) # true vector class number 2
    pred_vec.append(score)
    #print(predict)
    #cv2.imshow('imagem',cdist)

path = 'dataset/blackspot'
dirlist = []
dirlist = os.listdir(path)

sm = 0
for file in dirlist:

    img = image.load_img(path+'/'+file, target_size=(224, 224))
    orange = img_to_array(img)
    orange = preprocess_input(orange)
    orange = np.expand_dims(orange, axis=0)
    interpreter.set_tensor(input_details[0]['index'],orange)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])
    (cancro,frescas,grenning,pinta) = output_data[0]
    if(frescas>cancro and frescas>pinta and frescas>grenning):
        score = 1
    elif(cancro>frescas and cancro>pinta and cancro>grenning):
        score = 0
    elif(pinta>frescas and pinta>cancro and pinta>grenning):
        score = 3
    else:
        score = 2

    sm += score
    true_vec.append(3) # true vector class number 3
    pred_vec.append(score)
    #print(predict)
    #cv2.imshow('imagem',cdist)



### Compute confusion matrix to evaluate the accuracy of a classification.

In [52]:
classes = ['Canker', 'Fresh','Grenning','Black spot']
print(classification_report(true_vec, pred_vec, target_names=classes))
print(confusion_matrix(true_vec, pred_vec))

              precision    recall  f1-score   support

      Canker       0.98      0.98      0.98       148
       Fresh       1.00      1.00      1.00       164
    Grenning       1.00      1.00      1.00       176
  Black spot       0.98      0.98      0.98       138

    accuracy                           0.99       626
   macro avg       0.99      0.99      0.99       626
weighted avg       0.99      0.99      0.99       626

[[145   0   0   3]
 [  0 164   0   0]
 [  0   0 176   0]
 [  3   0   0 135]]
